# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainAgregarVehiculo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainAgregarVehiculo(object):
    def setupUi(self, MainAgregarVehiculo):
        MainAgregarVehiculo.setObjectName("MainAgregarVehiculo")
        MainAgregarVehiculo.resize(800, 600)
        MainAgregarVehiculo.setStyleSheet("QLabel{\n"
"color:white\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainAgregarVehiculo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 40, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txtRut = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRut.setGeometry(QtCore.QRect(250, 110, 301, 22))
        self.txtRut.setObjectName("txtRut")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(570, 110, 93, 28))
        self.btnBuscar.setObjectName("btnBuscar")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(250, 140, 301, 22))
        self.txtNombre.setReadOnly(True)
        self.txtNombre.setObjectName("txtNombre")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 140, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 260, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 300, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 340, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 380, 101, 16))
        self.label_7.setObjectName("label_7")
        self.txtPatente = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPatente.setGeometry(QtCore.QRect(250, 260, 301, 22))
        self.txtPatente.setReadOnly(False)
        self.txtPatente.setObjectName("txtPatente")
        self.txtMarca = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMarca.setGeometry(QtCore.QRect(250, 300, 301, 22))
        self.txtMarca.setReadOnly(False)
        self.txtMarca.setObjectName("txtMarca")
        self.txtModelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtModelo.setGeometry(QtCore.QRect(250, 340, 301, 22))
        self.txtModelo.setReadOnly(False)
        self.txtModelo.setObjectName("txtModelo")
        self.cboEstacionamiento = QtWidgets.QComboBox(self.centralwidget)
        self.cboEstacionamiento.setGeometry(QtCore.QRect(250, 380, 301, 22))
        self.cboEstacionamiento.setObjectName("cboEstacionamiento")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(570, 460, 93, 28))
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnIrEstacionamientos = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnIrEstacionamientos.setGeometry(QtCore.QRect(270, 170, 222, 48))
        self.btnIrEstacionamientos.setObjectName("btnIrEstacionamientos")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(130, 460, 93, 28))
        self.btnCancelar.setObjectName("btnCancelar")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(-550, -50, 1461, 631))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("w2.jpg"))
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.txtRut.raise_()
        self.btnBuscar.raise_()
        self.txtNombre.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.txtPatente.raise_()
        self.txtMarca.raise_()
        self.txtModelo.raise_()
        self.cboEstacionamiento.raise_()
        self.btnAgregar.raise_()
        self.btnIrEstacionamientos.raise_()
        self.btnCancelar.raise_()
        MainAgregarVehiculo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainAgregarVehiculo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainAgregarVehiculo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainAgregarVehiculo)
        self.statusbar.setObjectName("statusbar")
        MainAgregarVehiculo.setStatusBar(self.statusbar)

        self.retranslateUi(MainAgregarVehiculo)
        QtCore.QMetaObject.connectSlotsByName(MainAgregarVehiculo)

    def retranslateUi(self, MainAgregarVehiculo):
        _translate = QtCore.QCoreApplication.translate
        MainAgregarVehiculo.setWindowTitle(_translate("MainAgregarVehiculo", "MainWindow"))
        self.label.setText(_translate("MainAgregarVehiculo", "Agregar Vehiculo Residente"))
        self.label_2.setText(_translate("MainAgregarVehiculo", "RUT"))
        self.btnBuscar.setText(_translate("MainAgregarVehiculo", "Buscar"))
        self.label_3.setText(_translate("MainAgregarVehiculo", "Nombre"))
        self.label_4.setText(_translate("MainAgregarVehiculo", "Patente"))
        self.label_5.setText(_translate("MainAgregarVehiculo", "Marca"))
        self.label_6.setText(_translate("MainAgregarVehiculo", "Modelo"))
        self.label_7.setText(_translate("MainAgregarVehiculo", "Estacionamiento"))
        self.btnAgregar.setText(_translate("MainAgregarVehiculo", "Agregar"))
        self.btnIrEstacionamientos.setText(_translate("MainAgregarVehiculo", "Ir estacionamientos"))
        self.btnCancelar.setText(_translate("MainAgregarVehiculo", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainAgregarVehiculo = QtWidgets.QMainWindow()
    ui = Ui_MainAgregarVehiculo()
    ui.setupUi(MainAgregarVehiculo)
    MainAgregarVehiculo.show()
    sys.exit(app.exec_())

