# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainER.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainER(object):
    def setupUi(self, MainER):
        MainER.setObjectName("MainER")
        MainER.resize(1082, 636)
        MainER.setMinimumSize(QtCore.QSize(1082, 636))
        MainER.setMaximumSize(QtCore.QSize(1082, 636))
        MainER.setStyleSheet("QLabel{\n"
"color:white\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainER)
        self.centralwidget.setObjectName("centralwidget")
        self.txtRut = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRut.setGeometry(QtCore.QRect(370, 130, 321, 22))
        self.txtRut.setObjectName("txtRut")
        self.btnBuscarR = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscarR.setGeometry(QtCore.QRect(710, 130, 93, 28))
        self.btnBuscarR.setObjectName("btnBuscarR")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 200, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 320, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 240, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 280, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 360, 55, 16))
        self.label_3.setObjectName("label_3")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(370, 200, 431, 22))
        self.txtNombre.setObjectName("txtNombre")
        self.txtApellido = QtWidgets.QLineEdit(self.centralwidget)
        self.txtApellido.setGeometry(QtCore.QRect(370, 240, 431, 22))
        self.txtApellido.setObjectName("txtApellido")
        self.cboEdficio = QtWidgets.QComboBox(self.centralwidget)
        self.cboEdficio.setGeometry(QtCore.QRect(370, 280, 431, 21))
        self.cboEdficio.setObjectName("cboEdficio")
        self.cboDepartamento = QtWidgets.QComboBox(self.centralwidget)
        self.cboDepartamento.setGeometry(QtCore.QRect(370, 320, 431, 21))
        self.cboDepartamento.setObjectName("cboDepartamento")
        self.txtTelefono = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTelefono.setGeometry(QtCore.QRect(370, 350, 431, 22))
        self.txtTelefono.setObjectName("txtTelefono")
        self.btnEditar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditar.setGeometry(QtCore.QRect(740, 460, 93, 28))
        self.btnEditar.setObjectName("btnEditar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(250, 460, 93, 28))
        self.btnCancelar.setObjectName("btnCancelar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 130, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1091, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("w3.png"))
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(460, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label.raise_()
        self.txtRut.raise_()
        self.btnBuscarR.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.txtNombre.raise_()
        self.txtApellido.raise_()
        self.cboEdficio.raise_()
        self.cboDepartamento.raise_()
        self.txtTelefono.raise_()
        self.btnEditar.raise_()
        self.btnCancelar.raise_()
        self.label_7.raise_()
        self.label_12.raise_()
        MainER.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainER)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 26))
        self.menubar.setObjectName("menubar")
        MainER.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainER)
        self.statusbar.setObjectName("statusbar")
        MainER.setStatusBar(self.statusbar)

        self.retranslateUi(MainER)
        QtCore.QMetaObject.connectSlotsByName(MainER)

    def retranslateUi(self, MainER):
        _translate = QtCore.QCoreApplication.translate
        MainER.setWindowTitle(_translate("MainER", "MainWindow"))
        self.btnBuscarR.setText(_translate("MainER", "Buscar"))
        self.label_6.setText(_translate("MainER", "Nombre"))
        self.label_4.setText(_translate("MainER", "Departamento"))
        self.label_5.setText(_translate("MainER", "Apellido"))
        self.label_2.setText(_translate("MainER", "Edificio"))
        self.label_3.setText(_translate("MainER", "Telefono"))
        self.btnEditar.setText(_translate("MainER", "Guardar"))
        self.btnCancelar.setText(_translate("MainER", "Cancelar"))
        self.label_7.setText(_translate("MainER", "Rut"))
        self.label_12.setText(_translate("MainER", "Editar Residente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainER = QtWidgets.QMainWindow()
    ui = Ui_MainER()
    ui.setupUi(MainER)
    MainER.show()
    sys.exit(app.exec_())

