# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainAsignarDueño.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainAsignarDueno(object):
    def setupUi(self, MainAsignarDueno):
        MainAsignarDueno.setObjectName("MainAsignarDueno")
        MainAsignarDueno.resize(1091, 653)
        MainAsignarDueno.setStyleSheet("QLabel{\n"
"color:white\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainAsignarDueno)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cboEdficio = QtWidgets.QComboBox(self.centralwidget)
        self.cboEdficio.setGeometry(QtCore.QRect(430, 110, 251, 22))
        self.cboEdficio.setObjectName("cboEdficio")
        self.cboDepartamento = QtWidgets.QComboBox(self.centralwidget)
        self.cboDepartamento.setGeometry(QtCore.QRect(430, 150, 251, 22))
        self.cboDepartamento.setObjectName("cboDepartamento")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(700, 150, 93, 28))
        self.btnBuscar.setObjectName("btnBuscar")
        self.tableDueno = QtWidgets.QTableWidget(self.centralwidget)
        self.tableDueno.setGeometry(QtCore.QRect(280, 240, 521, 192))
        self.tableDueno.setObjectName("tableDueno")
        self.tableDueno.setColumnCount(4)
        self.tableDueno.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDueno.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDueno.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDueno.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDueno.setHorizontalHeaderItem(3, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 220, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 470, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtNuevoDueno = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNuevoDueno.setGeometry(QtCore.QRect(390, 470, 321, 21))
        self.txtNuevoDueno.setObjectName("txtNuevoDueno")
        self.btnGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGuardar.setGeometry(QtCore.QRect(720, 470, 93, 28))
        self.btnGuardar.setObjectName("btnGuardar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 1101, 621))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("w3.png"))
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.cboEdficio.raise_()
        self.cboDepartamento.raise_()
        self.btnBuscar.raise_()
        self.tableDueno.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.txtNuevoDueno.raise_()
        self.btnGuardar.raise_()
        MainAsignarDueno.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainAsignarDueno)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainAsignarDueno.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainAsignarDueno)
        self.statusbar.setObjectName("statusbar")
        MainAsignarDueno.setStatusBar(self.statusbar)

        self.retranslateUi(MainAsignarDueno)
        QtCore.QMetaObject.connectSlotsByName(MainAsignarDueno)

    def retranslateUi(self, MainAsignarDueno):
        _translate = QtCore.QCoreApplication.translate
        MainAsignarDueno.setWindowTitle(_translate("MainAsignarDueno", "MainWindow"))
        self.label.setText(_translate("MainAsignarDueno", "Asignar Dueño"))
        self.label_2.setText(_translate("MainAsignarDueno", "Edificio"))
        self.label_3.setText(_translate("MainAsignarDueno", "Departamento"))
        self.btnBuscar.setText(_translate("MainAsignarDueno", "Buscar"))
        item = self.tableDueno.horizontalHeaderItem(0)
        item.setText(_translate("MainAsignarDueno", "Rut Dueño"))
        item = self.tableDueno.horizontalHeaderItem(1)
        item.setText(_translate("MainAsignarDueno", "Nombre"))
        item = self.tableDueno.horizontalHeaderItem(2)
        item.setText(_translate("MainAsignarDueno", "Apellido"))
        item = self.tableDueno.horizontalHeaderItem(3)
        item.setText(_translate("MainAsignarDueno", "Telefono"))
        self.label_4.setText(_translate("MainAsignarDueno", "Datos Dueño"))
        self.label_5.setText(_translate("MainAsignarDueno", "Nuevo Dueño"))
        self.btnGuardar.setText(_translate("MainAsignarDueno", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainAsignarDueno = QtWidgets.QMainWindow()
    ui = Ui_MainAsignarDueno()
    ui.setupUi(MainAsignarDueno)
    MainAsignarDueno.show()
    sys.exit(app.exec_())

