# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainRV.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainRV(object):
    def setupUi(self, MainRV):
        MainRV.setObjectName("MainRV")
        MainRV.setEnabled(True)
        MainRV.resize(1036, 703)
        MainRV.setMinimumSize(QtCore.QSize(1036, 703))
        MainRV.setMaximumSize(QtCore.QSize(1036, 703))
        MainRV.setStyleSheet("QLabel{\n"
"color:white\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainRV)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 150, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 270, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 350, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 310, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 230, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 190, 55, 16))
        self.label_6.setObjectName("label_6")
        self.txtRut = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRut.setGeometry(QtCore.QRect(230, 150, 261, 22))
        self.txtRut.setObjectName("txtRut")
        self.txtNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNombre.setGeometry(QtCore.QRect(230, 190, 261, 22))
        self.txtNombre.setObjectName("txtNombre")
        self.txtApellido = QtWidgets.QLineEdit(self.centralwidget)
        self.txtApellido.setEnabled(True)
        self.txtApellido.setGeometry(QtCore.QRect(230, 230, 261, 22))
        self.txtApellido.setObjectName("txtApellido")
        self.txtTelefono = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTelefono.setGeometry(QtCore.QRect(230, 350, 261, 22))
        self.txtTelefono.setObjectName("txtTelefono")
        self.cboEdficio = QtWidgets.QComboBox(self.centralwidget)
        self.cboEdficio.setGeometry(QtCore.QRect(230, 270, 261, 21))
        self.cboEdficio.setObjectName("cboEdficio")
        self.cboDepartamento = QtWidgets.QComboBox(self.centralwidget)
        self.cboDepartamento.setGeometry(QtCore.QRect(230, 310, 261, 21))
        self.cboDepartamento.setObjectName("cboDepartamento")
        self.btnRegistrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistrar.setGeometry(QtCore.QRect(850, 540, 93, 28))
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(130, 540, 93, 28))
        self.btnCancelar.setObjectName("btnCancelar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 390, 55, 16))
        self.label_7.setObjectName("label_7")
        self.rbVehiculoNo = QtWidgets.QRadioButton(self.centralwidget)
        self.rbVehiculoNo.setGeometry(QtCore.QRect(230, 390, 95, 20))
        self.rbVehiculoNo.setStyleSheet("color:white")
        self.rbVehiculoNo.setChecked(True)
        self.rbVehiculoNo.setObjectName("rbVehiculoNo")
        self.rbVehiculoSi = QtWidgets.QRadioButton(self.centralwidget)
        self.rbVehiculoSi.setGeometry(QtCore.QRect(300, 390, 95, 20))
        self.rbVehiculoSi.setStyleSheet("color:white")
        self.rbVehiculoSi.setObjectName("rbVehiculoSi")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(640, 150, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(640, 230, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(640, 190, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(640, 270, 131, 21))
        self.label_11.setObjectName("label_11")
        self.txtPatente = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPatente.setEnabled(False)
        self.txtPatente.setGeometry(QtCore.QRect(760, 150, 201, 22))
        self.txtPatente.setObjectName("txtPatente")
        self.txtMarca = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMarca.setEnabled(False)
        self.txtMarca.setGeometry(QtCore.QRect(760, 190, 201, 22))
        self.txtMarca.setObjectName("txtMarca")
        self.txtModelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtModelo.setEnabled(False)
        self.txtModelo.setGeometry(QtCore.QRect(760, 230, 201, 22))
        self.txtModelo.setObjectName("txtModelo")
        self.cboNEstacionamento = QtWidgets.QComboBox(self.centralwidget)
        self.cboNEstacionamento.setEnabled(False)
        self.cboNEstacionamento.setGeometry(QtCore.QRect(800, 270, 161, 21))
        self.cboNEstacionamento.setObjectName("cboNEstacionamento")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(120, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QtCore.QRect(640, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.btnBuscarVisitaR = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscarVisitaR.setGeometry(QtCore.QRect(500, 150, 31, 28))
        self.btnBuscarVisitaR.setObjectName("btnBuscarVisitaR")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(430, 0, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(-410, -40, 1631, 791))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("w2.jpg"))
        self.label_15.setObjectName("label_15")
        self.label_15.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.txtRut.raise_()
        self.txtNombre.raise_()
        self.txtApellido.raise_()
        self.txtTelefono.raise_()
        self.cboEdficio.raise_()
        self.cboDepartamento.raise_()
        self.btnRegistrar.raise_()
        self.btnCancelar.raise_()
        self.label_7.raise_()
        self.rbVehiculoNo.raise_()
        self.rbVehiculoSi.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.txtPatente.raise_()
        self.txtMarca.raise_()
        self.txtModelo.raise_()
        self.cboNEstacionamento.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.btnBuscarVisitaR.raise_()
        self.label_14.raise_()
        MainRV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainRV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 26))
        self.menubar.setObjectName("menubar")
        MainRV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainRV)
        self.statusbar.setObjectName("statusbar")
        MainRV.setStatusBar(self.statusbar)

        self.retranslateUi(MainRV)
        QtCore.QMetaObject.connectSlotsByName(MainRV)

    def retranslateUi(self, MainRV):
        _translate = QtCore.QCoreApplication.translate
        MainRV.setWindowTitle(_translate("MainRV", "MainWindow"))
        self.label.setText(_translate("MainRV", "RUT"))
        self.label_2.setText(_translate("MainRV", "Edificio"))
        self.label_3.setText(_translate("MainRV", "Telefono"))
        self.label_4.setText(_translate("MainRV", "Departamento"))
        self.label_5.setText(_translate("MainRV", "Apellido"))
        self.label_6.setText(_translate("MainRV", "Nombre"))
        self.btnRegistrar.setText(_translate("MainRV", "Registrar"))
        self.btnCancelar.setText(_translate("MainRV", "Cancelar"))
        self.label_7.setText(_translate("MainRV", "Vehiculo"))
        self.rbVehiculoNo.setText(_translate("MainRV", "No"))
        self.rbVehiculoSi.setText(_translate("MainRV", "Sí"))
        self.label_8.setText(_translate("MainRV", "Patente"))
        self.label_9.setText(_translate("MainRV", "Modelo"))
        self.label_10.setText(_translate("MainRV", "Marca"))
        self.label_11.setText(_translate("MainRV", "N° Estacionamiento"))
        self.label_12.setText(_translate("MainRV", "Registrar Visita"))
        self.label_13.setText(_translate("MainRV", "Registrar Vehiculo"))
        self.btnBuscarVisitaR.setText(_translate("MainRV", "Ver"))
        self.label_14.setText(_translate("MainRV", "Registrar Visita"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainRV = QtWidgets.QMainWindow()
    ui = Ui_MainRV()
    ui.setupUi(MainRV)
    MainRV.show()
    sys.exit(app.exec_())

